# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=21w03a
yarn_mappings=21w03a+build.38
loader_version=0.14.21

# Mod Properties
mod_version = 2.3.3
maven_group = me.voidxwalker
archives_base_name = worldpreview


